spring.application.name=backend-ecommerce

# Datasource configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
spring.datasource.username=root
spring.datasource.password=Hoa01218816812
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
# Dùng "validate": 
# Hibernate sẽ kiểm tra xem code @Entity có khớp với bảng Flyway tạo ra không)
# Không thay đổi cấu trúc DB. 
# Chỉ đi đối chiếu xem các class @Entity có khớp hoàn toàn với các bảng trong DB không. 
# Nếu lệch 1 ly, ứng dụng lập tức báo lỗi và sập (Crash) không cho chạy.
spring.jpa.hibernate.ddl-auto=validate 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0
